sonar.projectKey=umer8707_E-commerce-schema
sonar.organization=umer8707
sonar.projectName=E-commerce Cart API
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/tests/**,**/seed.py,**/__pycache__/**,**/*.pyc

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
